### ISSUE TITLE
How to protect Vitepress pages with Keycloak

### ISSUE THREAD

**Issue by clabnet** [kalisio/vitepress-theme-kalisio#6]
Hi, 
thank you for sharing this code, I learning many things from this.
I would protect my vitepress documentation with Keycloak, both are running and up.

Your theme was integrated into my vitepress docs and is running fine.

I set KeycloakLayout to a test .md page, using frontmatter 
```
---
layout: KeycloakLayout
title: "Charts"
order: 2
---
```

`.vitepress/theme/index.js`
```
import KeycloakLayout from 'vitepress-theme-kalisio/layouts/KeycloakLayout.vue'
import theme from 'vitepress-theme-kalisio'
import './custom.css'
export default {
  extends: theme,
  KeycloakLayout: KeycloakLayout
}
```
but nothing happens.  I expect to see the Keycloak login page. 
Any suggestions please ? Thank's

**Comment by cnouguier** [comment]
Hi,
Can you try to modify your `index.js` file with the following code:

```
import theme from 'vitepress-theme-kalisio'
import './custom.css'
export default theme
```

The `KeycloakLayout` is already assigned to the `layout` when using the theme.

**Comment by clabnet** [comment]
@cnouguier  Thank you for the reply, but nothing happens.
In `config.ts` of .vitepress folder I have also added : 
```
themeConfig : {
...
    keycloak: {
      url: "https://xxxxxxxxxxx.cloudapp.azure.com/keycloak", // Url to the Keycloak instance
      realm: "xxxxxxxx", // Keycloak realm to be used
      clientId: "xxxxxxxxx", // Keycloak client id assigned to your site
      fallbackUrl: "https://xxxxxxxxxxx.azure.com", // Fallback Url if access is denied
    },
        useKeycloak: true,
...
}
```
Are there others changes to do ?

**Comment by cnouguier** [comment]
Hi @clabnet , we use to set the `useKeycloak` using environment variables. And  today is `useKeycloak` value must be a string. I will push a fix to handle a boolean as well

**Comment by cnouguier** [comment]
And I'll try to push a `docs` sample in the repository

**Comment by cnouguier** [comment]
@clabnet can you upgrade the theme and try it. Thanks :)

**Comment by clabnet** [comment]
Yes, it work using 
```
    useKeycloak: true,
```

Thank you @cnouguier
